#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cli_name='cpm'
author='Emerson Max de Medeiros Silva'
version='1.0'

function cli_help() {
    echo "Usage: $cli_name [command]

Custom Package Manager

commands:
    install    Run install for managers
    update     Run update for managers
    list       List all available managers
    help       Show this help
    version    Show version
"
}

if [[ $# < 1 ]]
then
    cli_help
    exit 1
fi

export CPM_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/cpm"
export CPM_MANAGERS_PATH="$CPM_CONFIG_PATH/managers"

function run_manager() {
    manager="$1"
    shift 1

    manager_path="$CPM_MANAGERS_PATH/$manager"
    if [[ ! -x "$manager_path" ]]
    then
        echo "$manager is not a valid manager"
        return
    fi

    $manager_path $@
}

function install_cmd() {
    if [[ $# == 0 ]]
    then
        echo "Usage: $cli_name install <managers>"
        exit 1
    fi

    for manager in $@
    do
        run_manager $manager install
    done
}

function update_cmd() {
    if [[ $# == 0 ]]
    then
        echo "Usage: $cli_name update <managers>"
        exit 1
    fi

    for manager in $@
    do
        run_manager $manager update
    done
}

function list_cmd() {
    for manager_path in $CPM_MANAGERS_PATH/*
    do
        if [[ ! -x "$manager_path" ]]
        then
            continue
        fi

        manager=$(basename $manager_path)
        echo $manager
    done
}

function help_cmd() {
    cli_help
    exit 0
}

function version_cmd() {
    echo "$cli_name $version"
}

action="$1"
shift 1
case $action in
    install)
        install_cmd $@
        ;;
    update)
        update_cmd $@
        ;;
    list)
        list_cmd
        ;;
    help)
        help_cmd $@
        ;;
    version)
        version_cmd
        ;;
    *)
        echo -e "Invalid command '$action'\n"
        cli_help
        ;;
esac
